"""empty message

Revision ID: 49e9ea89b84e
Revises: 38c5df63514f
Create Date: 2023-10-08 11:51:27.680675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49e9ea89b84e'
down_revision = '38c5df63514f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discussion', schema=None) as batch_op:
        batch_op.alter_column('observation_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discussion', schema=None) as batch_op:
        batch_op.alter_column('observation_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
