"""add likes

Revision ID: 50e5601abc42
Revises: 
Create Date: 2023-10-05 00:35:49.348673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50e5601abc42'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
       op.create_table(
        'likes',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('user_id', sa.Integer(), sa.ForeignKey('users.id'), nullable=False),
        sa.Column('discussion_id', sa.Integer(), sa.ForeignKey('discussions.id')),
        sa.Column('observation_id', sa.Integer(), sa.ForeignKey('observations.id')),
        sa.Column('timestamp', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    )
   
#  ### end Alembic commands ###