"""empty message

Revision ID: fa6115cc8355
Revises: 49e9ea89b84e
Create Date: 2023-10-08 17:42:37.028161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa6115cc8355'
down_revision = '49e9ea89b84e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('like', schema=None) as batch_op:
        batch_op.alter_column('observation_id',
               existing_type=sa.INTEGER(),
               nullable=False)
       # batch_op.drop_constraint('user.id', type_='foreignkey')
        batch_op.drop_column('discussion_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('like', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discussion_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('observation.id', 'discussion', ['discussion_id'], ['id'])
        batch_op.alter_column('observation_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
